In [1]:
import numpy as np

In [2]:
# %pip install notebook numpy

In [3]:
np.__version__

'2.1.3'

In [ ]:
np.array([1, 2, 3])
np.array([1, 2, 3], dtype=np.int32)
np.array([1, 2, 3], dtype=np.float32)
np.array([1, 2, 3], dtype=np.float64)
np.array([1, 2, 3], dtype=np.int64)
np.array([1, 2, 3], dtype=np.uint8)
np.array([1, 2, 3], dtype=np.uint16)
np.array([1, 2, 3], dtype=np.uint32)
np.array([1, 2, 3], dtype=np.uint64)
np.array([1, 2, 3], dtype=np.bool)
np.array([1, 2, 3], dtype=np.complex64)
np.array([1, 2, 3], dtype=np.complex128)

array([1, 2, 3])

In [19]:
arr = np.array([1, 2, 3])
type(arr)

numpy.ndarray

In [20]:
arr.dtype

dtype('int64')

In [21]:
arr = np.array([1, 2.4, 3])
type(arr)
arr.dtype

dtype('float64')

In [22]:
arr = np.array([1, 2.4, 3], dtype=np.int32)
type(arr)
arr.dtype

dtype('int32')

In [ ]:
arr

array([1, 2, 3], dtype=int32)

In [24]:
arr = np.array(["Apple", "Banana", "Orange", "Mango"])
print(arr)

['Apple' 'Banana' 'Orange' 'Mango']


In [25]:
arr = np.array(["Apple", "Banana", "Orange", "Mango",3.4])
print(arr)

['Apple' 'Banana' 'Orange' 'Mango' '3.4']


type of numpy array all element is same

In [26]:
arr = np.array([1, 2.4, 3], dtype=str)
type(arr)
print(arr.dtype)
arr

<U3


array(['1', '2.4', '3'], dtype='<U3')

In [27]:
print(arr.size)
print(arr.shape)
print(arr.ndim)

3
(3,)
1


In [28]:
np.zeros(5, dtype=float)
np.zeros((5, 5), dtype=int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [29]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [30]:
arr = np.zeros((3,4))

In [31]:
arr[0] = [1, 2, 3]

ValueError: could not broadcast input array from shape (3,) into shape (4,)

In [33]:
arr[0] = [1, 2, 3, 4]
arr

array([[1., 2., 3., 4.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
arr[:,2] = [99, 100, 101]
arr

array([[  1.,   2.,  99.,   4.],
       [  0.,   0., 100.,   0.],
       [  0.,   0., 101.,   0.]])

In [37]:
np.ones(5)
np.ones((5, 5))
np.ones((5, 5), dtype=np.int32)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [38]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
np.eye(3,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [41]:
np.eye(3,4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
np.eye(3,4, k=-1)

array([[0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [45]:
np.full(3, 4)

array([4, 4, 4])

In [47]:
np.full((3, 4), 9.4)

array([[9.4, 9.4, 9.4, 9.4],
       [9.4, 9.4, 9.4, 9.4],
       [9.4, 9.4, 9.4, 9.4]])

In [49]:
np.full((3, 4), 9.4, dtype=np.int32)

array([[9, 9, 9, 9],
       [9, 9, 9, 9],
       [9, 9, 9, 9]], dtype=int32)

In [50]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
np.arange(1,10,3)

array([1, 4, 7])

In [52]:
np.arange(1,10,0.7)

array([1. , 1.7, 2.4, 3.1, 3.8, 4.5, 5.2, 5.9, 6.6, 7.3, 8. , 8.7, 9.4])

In [53]:
np.arange(1,10.2,3)

array([ 1.,  4.,  7., 10.])

In [54]:
np.arange(1,10,3, dtype=float)

array([1., 4., 7.])

In [56]:
np.linspace(0, 10, 9)

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [57]:
np.linspace(0, 10)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [ ]:
np.linspace(0, 10, 7, retstep=True)

(array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
         8.33333333, 10.        ]),
 np.float64(1.6666666666666667))

In [59]:
np.linspace(0, 10, 7, retstep=True, dtype=int)

(array([ 0,  1,  3,  5,  6,  8, 10]), np.float64(1.6666666666666667))

In [ ]:
np.random.rand(4)
np.random.rand(4,3)  # 0 to 1 random values

array([[0.71650484, 0.2893288 , 0.76227012],
       [0.20336478, 0.03430284, 0.55837574],
       [0.01297648, 0.47783632, 0.22805423],
       [0.46838805, 0.56784404, 0.90980825]])

In [ ]:
np.random.randn(3)  

array([ 0.08866593, -0.08393628, -0.78141097])

In [64]:
np.random.randn(3,4)

array([[-0.19604017,  1.71009547, -0.06808222,  0.98839844],
       [ 0.08550983, -0.62711296, -0.02970962, -1.43210876],
       [ 1.30881814, -0.32165027, -0.24284489,  0.61646036]])

In [65]:
np.random.randint(0, 10, 4)

array([1, 5, 3, 7])

In [66]:
np.random.randint(0, 10, (2,4))

array([[0, 0, 5, 4],
       [2, 0, 2, 8]])

In [67]:
np.random.uniform
np.random.choice
np.random.normal

<bound method RandomState.normal of RandomState(MT19937) at 0x76D50212BD40>

In [68]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [77]:
arr2 = np.reshape(arr, (6, ))
arr2.shape

(6,)

In [78]:
arr2.ndim

1

In [79]:
arr = np.random.randint(33, 3333, (9,8))

In [80]:
arr

array([[ 325,  885,  798,  863, 2033,  629, 3130, 2456],
       [2275, 1059,  365, 2543, 2231, 1949, 2442,  177],
       [1101, 3180, 2161, 2425,  231, 2642, 2857, 2922],
       [1228, 3026,  309, 2400,  525, 2291, 3095,  984],
       [1960, 2794,  194, 1381, 2163, 3043, 1314,  505],
       [3157,  992,  136, 2325, 1326, 3156,  988, 2845],
       [2910, 1194,  286, 1984,  916, 2982, 1744, 3113],
       [ 368, 2141, 2613, 2151, 2849,  106, 2187, 1137],
       [ 887, 1954, 2487, 2331,  511, 3241, 1844,  293]])

In [81]:
np.max(arr)

np.int64(3241)

In [82]:
np.max(arr, axis=1)

array([3130, 2543, 3180, 3095, 3043, 3157, 3113, 2849, 3241])

In [83]:
np.argmax(arr)

np.int64(69)

In [ ]:
np.argmax(arr, axis=1)  # Find the index of the maximum value along the specified axis.

array([6, 3, 1, 6, 5, 0, 7, 4, 5])

In [86]:
arr1 = np.random.randint(0,10, (2,3))
arr2 = np.random.randint(0,10, (2,3))


In [87]:
np.concatenate([arr1, arr2])

array([[7, 0, 9],
       [3, 2, 7],
       [9, 2, 8],
       [8, 3, 3]])

In [88]:
np.concatenate([arr1, arr2], axis=1)

array([[7, 0, 9, 9, 2, 8],
       [3, 2, 7, 8, 3, 3]])

In [90]:
arr1

array([[7, 0, 9],
       [3, 2, 7]])

In [89]:
np.sort(arr1)

array([[0, 7, 9],
       [2, 3, 7]])

In [93]:
np.sort(arr1, axis=0)

array([[3, 0, 7],
       [7, 2, 9]])

In [94]:
arr = np.random.rand(7, 8)

In [95]:
arr

array([[0.25968389, 0.37119732, 0.02132657, 0.22214175, 0.8303244 ,
        0.20871942, 0.42984958, 0.79463182],
       [0.51164716, 0.10530602, 0.46011004, 0.08496996, 0.94239652,
        0.74143503, 0.10279543, 0.10200721],
       [0.79317505, 0.61023552, 0.72174345, 0.76774662, 0.96588262,
        0.10047359, 0.52355119, 0.78046983],
       [0.87608084, 0.45979561, 0.8364668 , 0.34709554, 0.62560868,
        0.54055357, 0.02442337, 0.76595161],
       [0.32702518, 0.96953283, 0.9340739 , 0.78254996, 0.04380087,
        0.51148093, 0.42143122, 0.5837366 ],
       [0.61321022, 0.36325309, 0.63979683, 0.07342094, 0.53926102,
        0.8450675 , 0.94874704, 0.40565127],
       [0.98598537, 0.74894477, 0.7958274 , 0.60392707, 0.76821981,
        0.65438121, 0.53404315, 0.36477998]])

In [97]:
arr[1:5,2:7]

array([[0.46011004, 0.08496996, 0.94239652, 0.74143503, 0.10279543],
       [0.72174345, 0.76774662, 0.96588262, 0.10047359, 0.52355119],
       [0.8364668 , 0.34709554, 0.62560868, 0.54055357, 0.02442337],
       [0.9340739 , 0.78254996, 0.04380087, 0.51148093, 0.42143122]])

In [99]:
arr[1:5:3,2:7:2]

array([[0.46011004, 0.94239652, 0.10279543],
       [0.9340739 , 0.04380087, 0.42143122]])

In [100]:
arr[::3,::2]

array([[0.25968389, 0.02132657, 0.8303244 , 0.42984958],
       [0.87608084, 0.8364668 , 0.62560868, 0.02442337],
       [0.98598537, 0.7958274 , 0.76821981, 0.53404315]])

In [102]:
arr[1] = 1, 2, 3, 4, 5, 6, 7, 8

In [103]:
arr

array([[0.25968389, 0.37119732, 0.02132657, 0.22214175, 0.8303244 ,
        0.20871942, 0.42984958, 0.79463182],
       [1.        , 2.        , 3.        , 4.        , 5.        ,
        6.        , 7.        , 8.        ],
       [0.79317505, 0.61023552, 0.72174345, 0.76774662, 0.96588262,
        0.10047359, 0.52355119, 0.78046983],
       [0.87608084, 0.45979561, 0.8364668 , 0.34709554, 0.62560868,
        0.54055357, 0.02442337, 0.76595161],
       [0.32702518, 0.96953283, 0.9340739 , 0.78254996, 0.04380087,
        0.51148093, 0.42143122, 0.5837366 ],
       [0.61321022, 0.36325309, 0.63979683, 0.07342094, 0.53926102,
        0.8450675 , 0.94874704, 0.40565127],
       [0.98598537, 0.74894477, 0.7958274 , 0.60392707, 0.76821981,
        0.65438121, 0.53404315, 0.36477998]])

In [ ]:
arr[[1, 2, 5],:]

IndexError: shape mismatch: indexing arrays could not be broadcast together with shapes (3,) (2,) 

In [117]:
arr[:,[1, 2, 5]]

array([[0.37119732, 0.02132657, 0.20871942],
       [2.        , 3.        , 6.        ],
       [0.61023552, 0.72174345, 0.10047359],
       [0.45979561, 0.8364668 , 0.54055357],
       [0.96953283, 0.9340739 , 0.51148093],
       [0.36325309, 0.63979683, 0.8450675 ],
       [0.74894477, 0.7958274 , 0.65438121]])

In [118]:
arr>0.1

array([[ True,  True, False,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True, False,  True],
       [ True,  True,  True,  True, False,  True,  True,  True],
       [ True,  True,  True, False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True]])

In [ ]:
arr[(arr>0.1) & (arr<0.9)]  # bracket is must also "and, or is not allowed"

array([0.25968389, 0.37119732, 0.22214175, 0.8303244 , 0.20871942,
       0.42984958, 0.79463182, 0.79317505, 0.61023552, 0.72174345,
       0.76774662, 0.10047359, 0.52355119, 0.78046983, 0.87608084,
       0.45979561, 0.8364668 , 0.34709554, 0.62560868, 0.54055357,
       0.76595161, 0.32702518, 0.78254996, 0.51148093, 0.42143122,
       0.5837366 , 0.61321022, 0.36325309, 0.63979683, 0.53926102,
       0.8450675 , 0.40565127, 0.74894477, 0.7958274 , 0.60392707,
       0.76821981, 0.65438121, 0.53404315, 0.36477998])

In [125]:
arr1 % arr2
arr1 + arr2
arr1 - arr2
arr1 * arr2
arr1 / arr2
arr1 ** 3
arr1 // arr2


arr1 //3
arr1 % 3
arr1 + 3
arr1 - 3
arr1 * 3
arr1 / 3



array([[2.33333333, 0.        , 3.        ],
       [1.        , 0.66666667, 2.33333333]])

In [126]:
np.sum(arr1)

np.int64(28)

In [129]:
np.sum(arr, axis=0)

array([ 4.85516054,  5.52295914,  6.94923495,  6.79688188,  8.7730974 ,
        8.86067623,  9.88204554, 11.69522111])

In [ ]:
np.prod(arr)
np.meand(arr)
np.std(arr)
np.var(arr)
np.median(arr)
np.min(arr)
np.log(arr)
np.cos(arr)
np.sin(arr)
np.exp(arr)
np.sqrt(arr)

In [130]:
np.sqrt?

Call signature:  np.sqrt(*args, **kwargs)
Type:            ufunc
String form:     <ufunc 'sqrt'>
File:            ~/.local/lib/python3.10/site-packages/numpy/__init__.py
Docstring:      
sqrt(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Return the non-negative square-root of an array, element-wise.

Parameters
----------
x : array_like
    The values whose square-roots are required.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain 

You're on the right track with the commands you've already explored! To cover the 20% of NumPy commands that are most commonly used in data science, here are additional essential commands and explanations to fill any gaps:

---

### Array Creation
- **`np.empty(shape)`**: Creates an uninitialized array with a given shape. Useful for performance optimization when you will overwrite all values.
- **`np.identity(n)`**: Creates an identity matrix of size `n x n`.

---

### Array Properties
- **`arr.size`**: Total number of elements in the array (already covered but crucial).
- **`arr.shape`**: Shape of the array (dimensions).
- **`arr.ndim`**: Number of dimensions.
- **`arr.itemsize`**: Size of each array element in bytes.
- **`arr.nbytes`**: Total memory consumed by the array (in bytes).

---

### Statistical and Aggregate Functions
- **`np.mean(arr, axis=None)`**: Mean value along a specified axis.
- **`np.median(arr, axis=None)`**: Median value.
- **`np.var(arr, axis=None)`**: Variance.
- **`np.std(arr, axis=None)`**: Standard deviation.
- **`np.cumsum(arr, axis=None)`**: Cumulative sum.
- **`np.cumprod(arr, axis=None)`**: Cumulative product.
- **`np.percentile(arr, q, axis=None)`**: Computes the `q`th percentile.

---

### Array Manipulation
- **`np.hstack((arr1, arr2))`**: Stacks arrays horizontally.
- **`np.vstack((arr1, arr2))`**: Stacks arrays vertically.
- **`np.dstack((arr1, arr2))`**: Stacks arrays along a new third axis.
- **`np.split(arr, sections, axis=0)`**: Splits an array into sections along an axis.
- **`np.tile(arr, reps)`**: Repeats the array for the specified repetitions.

---

### Linear Algebra
- **`np.dot(arr1, arr2)`**: Dot product of two arrays.
- **`np.linalg.inv(arr)`**: Inverse of a square matrix.
- **`np.linalg.det(arr)`**: Determinant of a square matrix.
- **`np.linalg.eig(arr)`**: Eigenvalues and eigenvectors of a square matrix.
- **`np.linalg.svd(arr)`**: Singular Value Decomposition.

---

### Boolean Indexing and Conditional Logic
- **`np.where(condition, x, y)`**: Element-wise selection based on a condition.
- **`np.any(arr, axis=None)`**: Checks if any elements are `True`.
- **`np.all(arr, axis=None)`**: Checks if all elements are `True`.

---

### Advanced Random Sampling
- **`np.random.seed(seed)`**: Sets the seed for reproducibility.
- **`np.random.permutation(arr)`**: Randomly permutes elements or rows.
- **`np.random.shuffle(arr)`**: Shuffles the array in place.
- **`np.random.binomial(n, p, size)`**: Draws samples from a binomial distribution.

---

### Performance and Efficiency
- **`np.vectorize(func)`**: Converts a function to work element-wise on arrays.
- **`np.meshgrid(x, y)`**: Generates coordinate grids, useful for plotting.

---

### Array Comparison
- **`np.array_equal(arr1, arr2)`**: Checks if two arrays are equal.
- **`np.isclose(arr1, arr2, rtol, atol)`**: Checks if elements are approximately equal within tolerance.

---

This list builds on your current knowledge while adding practical commands used heavily in data science. Practice combining these functions to manipulate data effectively!

Here’s an expanded list of NumPy commands that are extremely useful for data scientists, with additional categories to ensure comprehensive coverage:  

---

### Array Creation (Advanced)  
- **`np.arange(start, stop, step)`**: Generates values in a range with a specific step (already covered, but crucial).  
- **`np.linspace(start, stop, num)`**: Generates evenly spaced values between two numbers (already covered).  
- **`np.geomspace(start, stop, num)`**: Generates evenly spaced values on a logarithmic scale.  
- **`np.fromfunction(func, shape)`**: Creates an array using a function for each coordinate.  
- **`np.fromiter(iterable, dtype)`**: Creates an array from an iterable object.  

---

### Array Indexing and Slicing  
- **`np.take(arr, indices, axis)`**: Extracts specific elements based on indices.  
- **`np.put(arr, indices, values)`**: Replaces specific elements based on indices.  
- **`np.choose(choices, indices)`**: Constructs an array by picking values based on indices.  
- **`np.extract(condition, arr)`**: Returns elements of `arr` that satisfy the condition.  

---

### Broadcasting and Tile Operations  
- **`np.broadcast_to(arr, shape)`**: Broadcasts an array to a specified shape.  
- **`np.expand_dims(arr, axis)`**: Adds an axis to the array.  
- **`np.squeeze(arr, axis)`**: Removes axes of size 1.  
- **`np.repeat(arr, repeats, axis)`**: Repeats elements of an array.  

---

### Matrix Operations  
- **`np.outer(arr1, arr2)`**: Computes the outer product of two vectors.  
- **`np.inner(arr1, arr2)`**: Computes the inner product of two vectors.  
- **`np.linalg.matrix_rank(arr)`**: Computes the rank of a matrix.  
- **`np.trace(arr)`**: Returns the sum of diagonal elements.  
- **`np.linalg.solve(a, b)`**: Solves a linear system of equations.  

---

### Statistical and Probability Operations  
- **`np.corrcoef(arr1, arr2)`**: Computes Pearson correlation coefficients.  
- **`np.cov(arr1, arr2)`**: Computes the covariance matrix.  
- **`np.histogram(arr, bins)`**: Computes the histogram of a dataset.  
- **`np.bincount(arr)`**: Counts occurrences of integers in an array.  

---

### Sorting and Searching  
- **`np.partition(arr, kth)`**: Partially sorts the array based on the kth element.  
- **`np.searchsorted(arr, value)`**: Finds indices where elements should be inserted to maintain order.  
- **`np.unique(arr, return_counts)`**: Finds unique elements and optionally returns their counts.  

---

### Advanced Random Operations  
- **`np.random.normal(loc, scale, size)`**: Generates samples from a normal distribution.  
- **`np.random.poisson(lam, size)`**: Generates samples from a Poisson distribution.  
- **`np.random.choice(arr, size, replace, p)`**: Randomly selects elements from an array with probabilities.  
- **`np.random.multivariate_normal(mean, cov, size)`**: Draws samples from a multivariate normal distribution.  

---

### Utility Functions  
- **`np.clip(arr, a_min, a_max)`**: Limits values to a specified range.  
- **`np.round(arr, decimals)`**: Rounds values to a specified number of decimal places.  
- **`np.trunc(arr)`**: Truncates values (removes the fractional part).  
- **`np.floor(arr)`**: Rounds values down.  
- **`np.ceil(arr)`**: Rounds values up.  

---

### Logical Operations  
- **`np.logical_and(arr1, arr2)`**: Element-wise logical AND.  
- **`np.logical_or(arr1, arr2)`**: Element-wise logical OR.  
- **`np.logical_not(arr)`**: Element-wise logical NOT.  
- **`np.isin(arr, values)`**: Checks if elements are in a list of values.  

---

### Data Transformation and Shape Manipulation  
- **`np.flip(arr, axis)`**: Reverses the order of elements along an axis.  
- **`np.rot90(arr, k)`**: Rotates the array 90 degrees `k` times.  
- **`np.transpose(arr)`**: Swaps the axes of an array.  
- **`np.swapaxes(arr, axis1, axis2)`**: Interchanges two axes.  

---

### Handling Missing or Infinite Values  
- **`np.isnan(arr)`**: Checks for `NaN` values.  
- **`np.isinf(arr)`**: Checks for infinite values.  
- **`np.nan_to_num(arr)`**: Replaces `NaN` and infinity with numerical values.  

---

### Performance and Debugging  
- **`np.may_share_memory(arr1, arr2)`**: Checks if two arrays share memory.  
- **`np.memmap()`**: Memory-maps a file for efficient large-array handling.  
- **`np.set_printoptions()`**: Configures printing options for arrays.  

---

### Advanced Mathematical Operations  
- **`np.cross(arr1, arr2)`**: Computes the cross product.  
- **`np.tril(arr)`**: Extracts the lower triangular part of a matrix.  
- **`np.triu(arr)`**: Extracts the upper triangular part of a matrix.  
- **`np.hypot(x, y)`**: Computes the hypotenuse for two arrays.  

---

These commands, combined with those you already know, will ensure you're equipped with everything data scientists use frequently in NumPy for data manipulation, analysis, and preprocessing!

Here’s a list of additional crucial NumPy commands for data scientists, including **`np.where`**:  

---

### **Selection & Conditional Logic**
- **`np.where(condition, x, y)`**
- **`np.select(condlist, choicelist, default=0)`**
- **`np.choose(indices, choices)`**
- **`np.extract(condition, arr)`**
- **`np.nonzero(arr)`**

---

### **Array Manipulation**
- **`np.reshape(arr, newshape)`**
- **`np.transpose(arr)`**
- **`np.swapaxes(arr, axis1, axis2)`**
- **`np.expand_dims(arr, axis)`**
- **`np.squeeze(arr, axis=None)`**
- **`np.concatenate((arr1, arr2), axis)`**
- **`np.stack((arr1, arr2), axis=0)`**
- **`np.hstack((arr1, arr2))`**
- **`np.vstack((arr1, arr2))`**
- **`np.dstack((arr1, arr2))`**
- **`np.split(arr, indices_or_sections, axis)`**
- **`np.tile(arr, reps)`**
- **`np.repeat(arr, repeats, axis)`**

---

### **Sorting & Searching**
- **`np.sort(arr, axis=-1)`**
- **`np.argsort(arr, axis=-1)`**
- **`np.partition(arr, kth, axis=-1)`**
- **`np.searchsorted(arr, values)`**
- **`np.unique(arr, return_counts=False)`**
- **`np.isin(arr, test_elements)`**

---

### **Statistics & Aggregation**
- **`np.mean(arr, axis=None)`**
- **`np.median(arr, axis=None)`**
- **`np.std(arr, axis=None)`**
- **`np.var(arr, axis=None)`**
- **`np.sum(arr, axis=None)`**
- **`np.prod(arr, axis=None)`**
- **`np.cumsum(arr, axis=None)`**
- **`np.cumprod(arr, axis=None)`**
- **`np.percentile(arr, q, axis=None)`**
- **`np.corrcoef(arr1, arr2)`**
- **`np.cov(arr1, arr2)`**

---

### **Mathematical Operations**
- **`np.add(arr1, arr2)`**
- **`np.subtract(arr1, arr2)`**
- **`np.multiply(arr1, arr2)`**
- **`np.divide(arr1, arr2)`**
- **`np.power(arr, exp)`**
- **`np.sqrt(arr)`**
- **`np.log(arr)`**
- **`np.exp(arr)`**
- **`np.sin(arr)`**
- **`np.cos(arr)`**
- **`np.tan(arr)`**

---

### **Random Sampling**
- **`np.random.seed(seed)`**
- **`np.random.rand(d0, d1, ..., dn)`**
- **`np.random.randn(d0, d1, ..., dn)`**
- **`np.random.randint(low, high, size)`**
- **`np.random.choice(arr, size, replace, p)`**
- **`np.random.uniform(low, high, size)`**
- **`np.random.normal(loc, scale, size)`**

---

### **Linear Algebra**
- **`np.dot(arr1, arr2)`**
- **`np.matmul(arr1, arr2)`**
- **`np.linalg.inv(arr)`**
- **`np.linalg.det(arr)`**
- **`np.linalg.eig(arr)`**
- **`np.linalg.norm(arr)`**
- **`np.linalg.svd(arr)`**

---

### **Utilities**
- **`np.clip(arr, a_min, a_max)`**
- **`np.isnan(arr)`**
- **`np.isinf(arr)`**
- **`np.nan_to_num(arr)`**
- **`np.all(arr, axis=None)`**
- **`np.any(arr, axis=None)`**

This expanded list complements your learning and ensures you're aware of the most commonly used NumPy functions in data science!

You've covered a wide range of NumPy commands that are commonly used in data science. However, there are a few additional commands and concepts that are frequently used and might be helpful to know:

### Array Creation
- **`np.fromfile(file, dtype)`**: Construct an array from data in a text or binary file.
- **`np.loadtxt(fname, dtype)`**: Load data from a text file.
- **`np.genfromtxt(fname, dtype)`**: Load data from a text file with missing values handled.

### Array Manipulation
- **`np.ravel(arr)`**: Flatten the array.
- **`np.flatten(arr)`**: Return a copy of the array collapsed into one dimension.
- **`np.atleast_1d(*arys)`**: Convert inputs to arrays with at least one dimension.
- **`np.atleast_2d(*arys)`**: Convert inputs to arrays with at least two dimensions.
- **`np.atleast_3d(*arys)`**: Convert inputs to arrays with at least three dimensions.

### Broadcasting
- **`np.broadcast_arrays(*arrays)`**: Broadcast any number of arrays against each other.
- **`np.broadcast_to(array, shape)`**: Broadcast an array to a new shape.

### Mathematical Operations
- **`np.mod(arr1, arr2)`**: Return the element-wise remainder of division.
- **`np.floor_divide(arr1, arr2)`**: Return the largest integer smaller or equal to the division of the inputs.
- **`np.fmod(arr1, arr2)`**: Return the element-wise remainder of division.
- **`np.gcd(arr1, arr2)`**: Return the greatest common divisor of the inputs.
- **`np.lcm(arr1, arr2)`**: Return the least common multiple of the inputs.

### Statistical Operations
- **`np.quantile(arr, q, axis=None)`**: Compute the q-th quantile of the data along the specified axis.
- **`np.nanmean(arr, axis=None)`**: Compute the arithmetic mean along the specified axis, ignoring NaNs.
- **`np.nanstd(arr, axis=None)`**: Compute the standard deviation along the specified axis, ignoring NaNs.
- **`np.nanvar(arr, axis=None)`**: Compute the variance along the specified axis, ignoring NaNs.

### Sorting and Searching
- **`np.lexsort(keys, axis=-1)`**: Perform an indirect sort using a sequence of keys.
- **`np.msort(arr)`**: Return a copy of an array sorted along the first axis.

### Linear Algebra
- **`np.linalg.matrix_power(M, n)`**: Raise a square matrix to an integer power.
- **`np.linalg.matrix_rank(M)`**: Return matrix rank of array using SVD method.
- **`np.linalg.pinv(a)`**: Compute the (Moore-Penrose) pseudo-inverse of a matrix.

### Random Sampling
- **`np.random.logistic(loc, scale, size)`**: Draw samples from a logistic distribution.
- **`np.random.exponential(scale, size)`**: Draw samples from an exponential distribution.
- **`np.random.gamma(shape, scale, size)`**: Draw samples from a Gamma distribution.

### Utility Functions
- **`np.setdiff1d(arr1, arr2)`**: Find the set difference of two arrays.
- **`np.intersect1d(arr1, arr2)`**: Find the intersection of two arrays.
- **`np.union1d(arr1, arr2)`**: Find the union of two arrays.
- **`np.in1d(arr1, arr2)`**: Test whether each element of a 1-D array is also present in a second array.

### File I/O
- **`np.save(file, array)`**: Save an array to a binary file in NumPy `.npy` format.
- **`np.load(file)`**: Load an array from a `.npy` file.
- **`np.savez(file, *args, **kwds)`**: Save several arrays into a single file in uncompressed `.npz` format.
- **`np.savez_compressed(file, *args, **kwds)`**: Save several arrays into a single file in compressed `.npz` format.

### Performance and Efficiency
- **`np.einsum(subscripts, *operands)`**: Evaluates the Einstein summation convention on the operands.
- **`np.frombuffer(buffer, dtype)`**: Interpret a buffer as a 1-dimensional array.

### Advanced Mathematical Operations
- **`np.gradient(f, *varargs)`**: Return the gradient of an N-dimensional array.
- **`np.trapz(y, x, dx)`**: Integrate along the given axis using the composite trapezoidal rule.
- **`np.diff(a, n, axis)`**: Calculate the n-th discrete difference along the given axis.

### Data Transformation
- **`np.pad(array, pad_width, mode)`**: Pad an array.
- **`np.roll(a, shift, axis)`**: Roll array elements along a given axis.

These additional commands and concepts will further enhance your understanding and usage of NumPy in data science tasks.